{
  lib,
  rsshub,
  applyPatches,
  fetchPnpmDeps,
  pnpm_10,
  python3,
}:

rsshub.overrideAttrs (
  old:
  let
    # Inject playwright-extra + a stealth plugin (used by the custom routes
    # below) into package.json, then drop in the matching lockfile. The
    # lockfile is vendored and regenerated by ./update.py rather than carried
    # as a line-diff patch, which broke on every rsshub bump. The same two
    # deps must be listed in update.py's EXTRA_DEPS.
    patchedSrc = applyPatches {
      src = old.src;
      # --replace-fail aborts the build if the anchor is gone (e.g. rsshub
      # restructures package.json), instead of silently skipping like sed.
      postPatch = ''
        substituteInPlace package.json \
          --replace-fail '"dependencies": {' '"dependencies": {
            "playwright-extra": "^4.3.6",
            "puppeteer-extra-plugin-stealth": "^2.11.2",'
        cp ${./pnpm-lock.yaml} pnpm-lock.yaml
      '';
    };
  in
  {
    src = patchedSrc;

    pnpmDeps = fetchPnpmDeps {
      pname = old.pname;
      version = old.version;
      src = patchedSrc;
      fetcherVersion = 3;
      hash = "sha256-cK7fHzSylOGfkCtetTDi2C+k2yCF1YlJDb0YPL6pYmo=";
      pnpm = pnpm_10;
    };

    postPatch = (old.postPatch or "") + ''
      cp -R --no-preserve=mode ${./routes}/. lib/routes/
      find lib/routes \( -name '*.test.ts' -o -name '*.test.tsx' -o -name '*.test.mts' -o -name '*.test.mtsx' \) -delete
      mkdir -p lib/custom-tests
      cp -R ${./tests}/. lib/custom-tests/
    '';

    passthru = (old.passthru or { }) // {
      # Re-resolve the vendored lockfile + hash against the current nixpkgs
      # rsshub. `update.py --check` is the regression guard for version bumps.
      updateScript = [
        (lib.getExe python3)
        (builtins.toString ./update.py)
      ];
    };
  }
)
