keys:
  - &rhesus age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
creation_rules:
  - path_regex: home-manager/modules/secrets.yml
    key_groups:
      - age:
          - *rhesus
  - path_regex: terraform/secrets.enc.json
    key_groups:
      - age:
          - *rhesus
