keys:
  # Machines
  - &rhesus age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
  - &taps age1ylyrt2k6fl8eegqgc22acuvwqtwllw740ljypxavmsf4twc33y9q0x42vn
  - &pint age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # TODO: Replace with actual age key after first boot
  # Users
  - &seungwon age1axh7747a46nm8x6l42nalaptf6xh7q9t9z8qlwrwqg4xc89leqjsaaeu6r
creation_rules:
  # Terraform secrets
  - path_regex: terraform/secrets\.yaml
    key_groups:
      - age:
          - *seungwon
  # clan secrets (vars/)
  - path_regex: vars/per-machine/rhesus/.*
    key_groups:
      - age:
          - *rhesus
  - path_regex: vars/per-machine/taps/.*
    key_groups:
      - age:
          - *seungwon
          - *taps
  - path_regex: vars/per-machine/pint/.*
    key_groups:
      - age:
          - *pint
  # Taps machine secrets
  - path_regex: sops/machines/taps/.*
    key_groups:
      - age:
          - *seungwon
          - *taps
  # Shared secrets (sops/secrets/) - accessible from dev machine
  - path_regex: sops/secrets/.*/secret
    key_groups:
      - age:
          - *seungwon
          - *rhesus
  # Remote builder SSH keys
  - path_regex: sops/builders/.*/secret
    key_groups:
      - age:
          - *seungwon
          - *rhesus
