# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    access_key = "afcc8b0c7e07ef000418f004daf9d6b4"
    bucket     = "dots-tfstate"
    endpoints = {
      s3 = "https://a36871be6860124304dfb5c3b3eb8c1a.r2.cloudflarestorage.com"
    }
    key                         = "aws/terraform.tfstate"
    region                      = "auto"
    secret_key                  = "0fcf60e21518984b22e1e6fa898ca1ae4a9ea8d2556e9de6514581ad0e43b0aa"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    use_path_style              = true
  }
}
