# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket = "dots-tfstate"
    endpoints = {
      s3 = "https://a36871be6860124304dfb5c3b3eb8c1a.r2.cloudflarestorage.com"
    }
    key                         = "github/terraform.tfstate"
    region                      = "auto"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    use_path_style              = true
  }
}
