[aliases]
a = ["abandon"]
abs = ["absorb"]
bd = ["bookmark", "delete"]
bf = ["bookmark", "forget"]
bl = ["bookmark", "list"]
bla = ["bookmark", "list", "-a"]
bm = ["bookmark", "move"]
br = ["bookmark", "rename"]
bs = ["bookmark", "set"]
bt = ["bookmark", "track"]
c = ["commit"]
cap = ["config", "set", "--repo", "scope.cap"]
cm = ["commit", "-m"]
d = ["describe"]
df = ["diff"]
dfg = ["diff", "--git"]
dfn = ["diff", "--name-only"]
dfs = ["diff", "--stat"]
dm = ["describe", "-m"]
e = ["edit"]
el = ["evolog"]
examine = ["log", "-r", "@", "-p", "--git"]
fa = ["file", "annotate"]
fc = ["file", "chmod"]
fl = ["file", "list"]
float-cap = ["util", "exec", "--", "jj-float-cap"]
fresh = ["new", "trunk()"]
fs = ["file", "show"]
fx = ["fix"]
gcl = ["git", "clone"]
gf = ["git", "fetch"]
get = ["config", "get"]
gp = ["git", "push"]
gpb = ["git", "push", "--bookmark"]
gpc = ["git", "push", "--change"]
gpd = ["git", "push", "--deleted"]
init = ["git", "init", "--colocate"]
gra = ["git", "remote", "add"]
grl = ["git", "remote", "list"]
grm = ["git", "remote", "remove"]
grn = ["git", "remote", "rename"]
grs = ["git", "remote", "set-url"]
l = ["log", "-r", "stack()", "--reversed"]
j = ["log", "-r", "jj_git_junk()"]
jc = ["abandon", "jj_git_junk()"]
la = ["log", "-r", "all()"]
lr = ["log", "-r"]
ls = ["log", "--summary", "-r", "@"]
n = ["new"]
na = ["new", "-A"]
nb = ["new", "-B"]
nn = ["new", "--no-edit"]
nna = ["new", "--no-edit", "-A"]
nnb = ["new", "--no-edit", "-B"]
nx = ["next"]
ol = ["op", "log"]
pv = ["prev"]
rb = ["rebase"]
rbd = ["rebase", "-d"]
rbr = ["rebase", "-r"]
rbs = ["rebase", "-s"]
rc = ["rebase", "-r", "@", "-d", "trunk()"]
rst = ["rebase", "-s", "roots(stack())", "-d", "trunk()"]
ra = ["rebase", "-s", "roots(mutable())", "-d", "trunk()"]
rs = ["resolve"]
rsl = ["resolve", "--list"]
rsr = ["resolve", "-r"]
s = ["show"]
sg = ["show", "--git"]
set = ["config", "set", "--repo"]
sig = [
  "log",
  "--template",
  "change_id.short() ++ \" \" ++ format_signature_status(signature) ++ \" \" ++ description.first_line() ++ \"\\n\"",
]
sp = ["split"]
sq = ["squash"]
sqd = ["squash", "--from", "@-", "--into", "@"]
squ = ["squash", "--from", "@", "--into", "@-"]
ss = ["show", "--summary"]
stack = ["log", "-r", "stack()"]
swap = ["rebase", "-r", "@-", "-A", "@"]
topic = ["util", "exec", "--", "jj-topic"]
tug = ["util", "exec", "--", "jj-tug"]
trunk = ["config", "set", "--repo", "revset-aliases.\"trunk()\""]
unscope = ["util", "exec", "--", "jj-unscope"]
uncap = ["config", "unset", "--repo", "scope.cap"]
untopic = ["util", "exec", "--", "jj-untopic"]
untrunk = ["config", "unset", "--repo", "revset-aliases.\"trunk()\""]
unset = ["config", "unset", "--repo"]
w = ["workspace", "list"]
ws = ["workspace"]
wsa = ["workspace", "add"]
wsl = ["workspace", "list"]
wsf = ["workspace", "forget"]
wsu = ["workspace", "update-stale"]

[git]
sign-on-push = false
write-change-id-header = false

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"
"closest_pushable(to)" = "heads(::to & mutable() & ~description(exact:\"\") & (~empty() | merges()))"
"immutable_heads()" = "present(trunk()) | tags() | (untracked_remote_bookmarks() ~ untracked_remote_bookmarks(remote='rad') ~ untracked_remote_bookmarks(regex:'^patch(es)/', remote='rad'))"
"jj_git_junk()" = "heads(mutable() & description(exact:\"\")) ~ (empty() | @ | bookmarks() | remote_bookmarks())"
"mine()" = "author(exact:\"67085791+mulatta@users.noreply.github.com\")"
"stack()" = "trunk()..@"
"trunk()" = "latest(present(master@rad) | present(main@rad) | present(master@upstream) | present(main@upstream) | present(main@origin) | present(master@origin) | root())"
"unpushed()" = "remote_bookmarks()..@"

[template-aliases]
"format_short_id(id)" = "id.shortest(8)"
"format_short_signature(signature)" = "signature.name()"
"format_signature_status(sig)" = "if(sig, sig.status(), \"unsigned\")"
"format_timestamp(timestamp)" = "timestamp.ago()"

[colors]
"annotate recent commit author timestamp format" = "green"
"annotate stale commit author timestamp format" = "yellow"
"annotate old commit author timestamp format" = "red"

[templates]
draft_commit_description = "concat(\n  builtin_draft_commit_description,\n  \"\\nJJ: ignore-rest\\n\",\n  diff.git(),\n)\n"
file_annotate = '''
commit.commit_id().short(8) ++ " " ++
if(
  commit.author().timestamp().before("3 months ago"),
  label("annotate old", commit.author().timestamp().format("%Y-%m-%d")),
  if(
    commit.author().timestamp().before("1 month ago"),
    label("annotate stale", commit.author().timestamp().format("%Y-%m-%d")),
    label("annotate recent", commit.author().timestamp().format("%Y-%m-%d"))
  )
) ++ " " ++
content
'''

[ui]
default-command = ["log", "-r", "trunk() | stack()", "--reversed"]
movement.edit = true
pager = "less -FRX"

[user]
email = "67085791+mulatta@users.noreply.github.com"
name = "mulatta"
