# theme = "nightfox"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
cursorline = true
scroll-lines = 2
auto-info = true
indent-heuristic = "hybrid"
default-line-ending = "lf"
rulers = [120]
true-color = true
end-of-line-diagnostics = "hint"
popup-border = "all"
color-modes = true
text-width = 512
undercurl = false

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 3

[editor.smart-tab]
enable = true
supersede-menu = true

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.file-picker]
hidden = false
max-depth = 5
follow-symlinks = true
deduplicate-links = true
parents = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
separator = "︙"
left = ["mode", "spinner", "version-control", "file-base-name"]
center = ["register"]
right = ["diagnostics", "selections", "position", "file-encoding"]

[editor.statusline.mode]
normal = "\uF120"
insert = "[+]"
select = "[^]"

[editor.indent-guides]
render = true
character = "╎"

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "-"

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[keys.normal.space]
space = "file_picker"
w = ":w"
q = ":q"
Q = ":q!"
n = ":n"

# ===== KEYBINDINGS =====
[keys.normal.q]
q = ":bc"
Q = ":bc!"

[keys.normal]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

# Selection handling
esc = ["collapse_selection", "keep_primary_selection"]

# Tree-sitter navigation
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

# Buffer navigation improvements
"H" = ":buffer-previous"
"L" = ":buffer-next"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[keys.insert]
esc = "normal_mode"
S-tab = "move_parent_node_start"
C-l = "delete_char_backward"
C-h = "delete_char_forward"
C-A-k = "kill_to_line_end"
C-A-u = "kill_to_line_start"
C-w = "delete_word_backward"
