# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
data "sops_file" "cloudflare_token" {
  source_file = "${path.module}/../../vars/per-machine/taps/cloudflare-api/token/secret"
  input_type  = "raw"
}
