# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "mulatta-dots-tfstate"
    dynamodb_table = "dots-terraform-locks"
    encrypt        = true
    key            = "vultr/terraform.tfstate"
    region         = "ap-northeast-2"
  }
}
