[mulatta]
default = unread
from = seungwon <seungwon@mulatta.io>
aliases = seungwon <billings@mulatta.io>
source = notmuch://
query-map = ~/.config/aerc/querymap
outgoing = msmtp
copy-to = Sent Items
postpone = drafts
multi-file-strategy = act-all
folders = inbox,unread,urgent,newsletter,dev,research,finance,university,social,notifications,sent,drafts,junk,trash
folders-sort = inbox,unread,urgent,newsletter,dev,research,finance,university,social,notifications,sent,drafts,junk,trash
