[mulatta]
default = unread
from = seungwon <seungwon@mulatta.io>
source = notmuch:///Users/seungwon/.local/share/mail
query-map = /Users/seungwon/.config/aerc/querymap
maildir-store = /Users/seungwon/.local/share/mail/mulatta
outgoing = msmtp
copy-to = sent
postpone = drafts
multi-file-strategy = act-all
folders = inbox,unread,urgent,newsletter,dev,research,finance,university,social,notifications,sent,drafts,junk,trash
folders-sort = inbox,unread,urgent,newsletter,dev,research,finance,university,social,notifications,sent,drafts,junk,trash
