{
  pkgs,
  ...
}:
let
  domain = "mail.mulatta.io";
  baseDomain = "mulatta.io";
in
{
  # Stalwart Mail Server - All-in-one mail server
  # Provides: SMTP, IMAP, JMAP, CalDAV, CardDAV
  #
  # Architecture:
  #   - SMTP/IMAP: Stalwart handles TLS using nginx ACME certs
  #   - HTTP (JMAP, CalDAV, WebAdmin): nginx reverse proxy handles TLS
  #
  # DNS records managed by terraform/cloudflare/dns.tf
  # PTR record: Set via Vultr console (Reverse DNS)
  #
  # After deployment:
  #   1. Access admin UI at https://mail.mulatta.io/admin
  #   2. Login with fallback admin credentials (from sops secret)
  #   3. Create domain and user accounts
  #   4. DKIM keys are auto-generated by Stalwart

  services.stalwart-mail = {
    enable = true;
    openFirewall = true;

    settings = {
      server = {
        hostname = domain;

        tls = {
          enable = true;
          implicit = false;
        };

        listener = {
          smtp = {
            bind = [ "[::]:25" ];
            protocol = "smtp";
          };

          submissions = {
            bind = [ "[::]:465" ];
            protocol = "smtp";
            tls.implicit = true;
          };

          submission = {
            bind = [ "[::]:587" ];
            protocol = "smtp";
            tls.implicit = false;
          };

          imap = {
            bind = [ "[::]:143" ];
            protocol = "imap";
          };

          imaptls = {
            bind = [ "[::]:993" ];
            protocol = "imap";
            tls.implicit = true;
          };

          http = {
            bind = [ "127.0.0.1:8080" ];
            protocol = "http";
            tls.implicit = false;
          };
        };
      };

      # Use nginx ACME certificate
      certificate.default = {
        cert = "%{file:/var/lib/acme/${domain}/fullchain.pem}%";
        private-key = "%{file:/var/lib/acme/${domain}/key.pem}%";
        default = true;
      };

      resolver = {
        type = "system";
        public-suffix = [
          "file://${pkgs.publicsuffix-list}/share/publicsuffix/public_suffix_list.dat"
        ];
      };

      storage = {
        data = "rocksdb";
        fts = "rocksdb";
        blob = "rocksdb";
        lookup = "rocksdb";
        directory = "internal";
      };

      store.rocksdb = {
        type = "rocksdb";
        path = "/var/lib/stalwart-mail/data";
        compression = "lz4";
      };

      store.db = {
        type = "rocksdb";
        path = "/var/lib/stalwart-mail/db";
        compression = "lz4";
      };

      directory.internal = {
        type = "internal";
        store = "rocksdb";
      };

      # Fallback admin account - uses sops secret
      authentication.fallback-admin = {
        user = "admin";
        secret = "%{file:/run/secrets/vars/stalwart-admin/password}%";
      };

      session = {
        auth = {
          mechanisms = [
            {
              "if" = "listener != 'smtp'";
              "then" = "[plain, login]";
            }
            { "else" = false; }
          ];
          directory = [
            {
              "if" = "listener != 'smtp'";
              "then" = "'internal'";
            }
            { "else" = false; }
          ];
        };

        timeout = "5m";
        transfer-limit = "262144000";
        duration = "10m";
      };

      queue.notify = [
        {
          "if" = "rcpt_domain = '${baseDomain}'";
          "then" = "[orcpt]";
        }
        { "else" = "[]"; }
      ];

      spam-filter = {
        enable = true;
        resource = "file://${pkgs.stalwart-mail.passthru.spam-filter}/spam-filter.toml";
      };

      webadmin = {
        enable = true;
        path = "/var/cache/stalwart-mail";
        resource = "file://${pkgs.stalwart-mail.passthru.webadmin}/webadmin.zip";
      };

      tracing.stdout = {
        enable = true;
        level = "info";
        ansi = false;
      };

      tracer.stdout = {
        type = "stdout";
        enable = true;
        level = "info";
        ansi = false;
      };
    };
  };

  # Grant stalwart access to nginx ACME certs
  users.users.stalwart-mail.extraGroups = [ "acme" ];

  # Reload stalwart when certs are renewed
  security.acme.certs.${domain}.reloadServices = [ "stalwart-mail.service" ];

  systemd.services.stalwart-mail = {
    after = [
      "acme-${domain}.service"
      "acme-finished-${domain}.target"
    ];
    wants = [ "acme-finished-${domain}.target" ];
    serviceConfig = {
      ProtectClock = true;
      ProtectKernelLogs = true;
    };
  };
}
