[bindings]
quit = "ctrl + alt - q"
window_center = "ctrl + alt - c"
window_focus_east = "alt + ctrl - l"
window_virtual_north = "alt + ctrl - k"
window_virtual_south = "alt + ctrl - j"
window_focus_west = "alt + ctrl - h"
window_fullwidth = "ctrl + alt - m"
window_manage = "ctrl + alt - f"
window_nextdisplay = "ctrl + alt - n"
window_nextdisplaysend = "ctrl + alt + shift - n"
window_resize = "ctrl + alt - r"
window_shrink = "ctrl + alt + shift - r"
window_swap_east = "ctrl + alt + shift - l"
window_virtualmove_north = "ctrl + alt + shift - k"
window_virtualmove_south = "ctrl + alt + shift - j"
window_swap_west = "ctrl + alt + shift - h"

[options]
animation_speed = 14.0
focus_follows_mouse = true
mouse_follows_focus = false
preset_column_widths = [0.25, 0.33, 0.5, 0.66, 0.75]
